//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface Iperms
    {
        string perm_code { get; set; }
        string perm_name { get; set; }
        System.DateTime creation_date { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modification_date { get; set; }
        string last_modifier { get; set; }
    
        ICollection<Irole_perms> role_perms { get; set; }
        ICollection<Iuser_perms> user_perms { get; set; }
    } 
}
