//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IwebApp
    {
        int webAppID { get; set; }
        string surName { get; set; }
        string otherNames { get; set; }
        Nullable<System.DateTime> dob { get; set; }
        Nullable<int> maritalStatusID { get; set; }
        string sex { get; set; }
        int categoryID { get; set; }
        int clientTypeID { get; set; }
        Nullable<int> branchID { get; set; }
        bool approved { get; set; }
        bool denied { get; set; }
        string user_name { get; set; }
    
        IwebAppBank webAppBank { get; set; }
        IwebAppContact webAppContact { get; set; }
        IwebAppEmp webAppEmp { get; set; }
        IwebAppEmp2 webAppEmp2 { get; set; }
        IwebAppID webAppID1 { get; set; }
        IwebAppMailAddr webAppMailAddr { get; set; }
        IwebAppPhoto webAppPhoto { get; set; }
        IwebAppPhyAddr webAppPhyAddr { get; set; }
        IwebAppSalary webAppSalary { get; set; }
    } 
}
