//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public interface IcoreSecurityEntities : IDisposable
    {
    	int SaveChanges();
    	System.Data.Entity.Infrastructure.DbContextConfiguration Configuration {get;}
    	System.Data.Entity.Database Database {get;}
        IDbSet<roles> roles { get; set; }
        IDbSet<user_roles> user_roles { get; set; }
        IDbSet<users> users { get; set; }
        IDbSet<user_login_attempts> user_login_attempts { get; set; }
        IDbSet<modules> modules { get; set; }
        IDbSet<perms> perms { get; set; }
        IDbSet<role_perms> role_perms { get; set; }
        IDbSet<user_perms> user_perms { get; set; }
        IDbSet<cuser> cusers { get; set; }
        IDbSet<userAudit> userAudits { get; set; }
        IDbSet<webApp> webApps { get; set; }
        IDbSet<webAppBank> webAppBanks { get; set; }
        IDbSet<webAppContact> webAppContacts { get; set; }
        IDbSet<webAppEmp> webAppEmps { get; set; }
        IDbSet<webAppEmp2> webAppEmp2 { get; set; }
        IDbSet<webAppID> webAppIDs { get; set; }
        IDbSet<webAppMailAddr> webAppMailAddrs { get; set; }
        IDbSet<webAppPhoto> webAppPhotoes { get; set; }
        IDbSet<webAppPhyAddr> webAppPhyAddrs { get; set; }
        IDbSet<webAppSalary> webAppSalaries { get; set; }
        IDbSet<userError> userErrors { get; set; }
        IDbSet<authToken> authTokens { get; set; }
        IDbSet<accessLevel> accessLevels { get; set; }
        IDbSet<kerbero> kerberos { get; set; }
    }
}
