//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBankDown
    {
        public int clientID { get; set; }
        public string surName { get; set; }
        public string otherNames { get; set; }
        public string accountNumber { get; set; }
        public double initialAmount { get; set; }
        public double monthlyDeduction { get; set; }
        public string names { get; set; }
        public double tenure { get; set; }
        public string staffID { get; set; }
        public double balBF { get; set; }
        public double controllerDeduction { get; set; }
        public string comments { get; set; }
        public System.DateTime repaymentDate { get; set; }
    }
}
