//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCashFlow
    {
        public System.DateTime month { get; set; }
        public string loanProductName { get; set; }
        public string clientName { get; set; }
        public string loanID { get; set; }
        public decimal expected { get; set; }
        public decimal collectionRatio { get; set; }
    }
}
