//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClient
    {
        public int clientID { get; set; }
        public string clientName { get; set; }
        public string accountNumber { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string directions { get; set; }
        public string cityTown { get; set; }
        public string workPhone { get; set; }
        public string mobilePhone { get; set; }
        public string homePhone { get; set; }
        public string officeEmail { get; set; }
        public string personalEmail { get; set; }
        public byte[] image { get; set; }
        public System.DateTime DOB { get; set; }
        public string categoryName { get; set; }
        public int branchID { get; set; }
    }
}
