//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLoanStatement
    {
        public int clientID { get; set; }
        public string clientName { get; set; }
        public string accountNumber { get; set; }
        public int loanID { get; set; }
        public string loanNo { get; set; }
        public System.DateTime date { get; set; }
        public string Description { get; set; }
        public double Dr { get; set; }
        public double Cr { get; set; }
        public int sortCode { get; set; }
        public bool isAgentLoan { get; set; }
        public string agentName { get; set; }
        public string agentNo { get; set; }
        public double balance { get; set; }
        public System.DateTime disbursementDate { get; set; }
        public double amountApproved { get; set; }
        public double loanTenure { get; set; }
        public System.DateTime expiryDate { get; set; }
        public double principalBalance { get; set; }
        public double Arrears { get; set; }
    }
}
