//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLoans4
    {
        public int clientID { get; set; }
        public string clientName { get; set; }
        public string accountNumber { get; set; }
        public int loanID { get; set; }
        public string loanNo { get; set; }
        public System.DateTime date { get; set; }
        public double principal { get; set; }
        public double interest { get; set; }
        public double addInt { get; set; }
        public double procFee { get; set; }
        public double paidPrinc { get; set; }
        public double paidInt { get; set; }
        public double paidAddInt { get; set; }
        public double paidProcFee { get; set; }
        public string loanTypeName { get; set; }
        public double writtenOff { get; set; }
    }
}
