//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMember
    {
        public int clientID { get; set; }
        public string clientName { get; set; }
        public string accountNumber { get; set; }
        public string sex { get; set; }
        public System.DateTime DOB { get; set; }
        public string officeEmail { get; set; }
        public string homePhone { get; set; }
        public string mobilePhone { get; set; }
        public string workPhone { get; set; }
        public string cityTown { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string directions { get; set; }
        public string personalEmail { get; set; }
        public System.DateTime joinedDate { get; set; }
        public double sharesBalance { get; set; }
        public string chapterName { get; set; }
        public System.DateTime dateFormed { get; set; }
        public string docRegistrationNumber { get; set; }
        public string postalAddress { get; set; }
        public string town { get; set; }
        public string emailAddress { get; set; }
        public string telePhoneNumber { get; set; }
        public double pricePerShare { get; set; }
        public Nullable<double> savingsBalance { get; set; }
        public Nullable<double> depositBalance { get; set; }
        public Nullable<int> loansbalance { get; set; }
        public Nullable<int> loanCount { get; set; }
        public string accountStatus { get; set; }
        public string idType { get; set; }
        public string idNumber { get; set; }
    }
}
