//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProjection
    {
        public int clientID { get; set; }
        public string clientName { get; set; }
        public string accountNumber { get; set; }
        public int loanID { get; set; }
        public string loanNo { get; set; }
        public System.DateTime repaymentDate { get; set; }
        public double principalBalance { get; set; }
        public double interestBalance { get; set; }
        public double applicationFeeBalance { get; set; }
        public double processingFeeBalance { get; set; }
        public double commissionBalance { get; set; }
        public string TypeOfBalance { get; set; }
    }
}
