//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwregularSusuContribution
    {
        public string clientName { get; set; }
        public int clientID { get; set; }
        public string accountNumber { get; set; }
        public System.DateTime contributionDate { get; set; }
        public double amount { get; set; }
        public string cashierUsername { get; set; }
        public string regularSusuAccountNo { get; set; }
        public int modeOfPaymentID { get; set; }
        public string modeOfPaymentName { get; set; }
    }
}
