//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	namespace coreLogic
	{
	
    using System;
    using System.Collections.Generic;
    
    public interface IarInvoiceLine
    {
        long arInvoiceLineId { get; set; }
        long arInvoiceId { get; set; }
        long inventoryItemId { get; set; }
        int lineNumber { get; set; }
        string description { get; set; }
        Nullable<int> acct_id { get; set; }
        double unitPrice { get; set; }
        double quantity { get; set; }
        int unitOfMeasurementId { get; set; }
        double discountAmount { get; set; }
        double discountPercentage { get; set; }
        double totalAmount { get; set; }
        double netAmount { get; set; }
        bool isVat { get; set; }
        bool isNHIL { get; set; }
        bool isWith { get; set; }
        double unitPriceLocal { get; set; }
        double discountAmountLocal { get; set; }
        double totalAmountLocal { get; set; }
        double netAmountLocal { get; set; }
        int accountId { get; set; }
        int discountAccountId { get; set; }
        int vatAccountId { get; set; }
        int nhilAccountId { get; set; }
        int withAccountId { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        System.DateTime modified { get; set; }
    
        IarInvoice arInvoice { get; set; }
        ICollection<IcreditMemoLine> creditMemoLines { get; set; }
    } 
}
