//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	namespace coreLogic
	{
	
    using System;
    using System.Collections.Generic;
    
    public interface IassemblyLine
    {
        int assemblyLineId { get; set; }
        string assemblyLineName { get; set; }
        short assemblyLineTypeId { get; set; }
        int endProductId { get; set; }
        short factoryId { get; set; }
        int supervisorStaffId { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        System.DateTime modified { get; set; }
    
        Iproduct product { get; set; }
        IassemblyLineType assemblyLineType { get; set; }
        Ifactory factory { get; set; }
        ICollection<IassemblyWorkStage> assemblyWorkStages { get; set; }
        ICollection<ImanufacturingCalender> manufacturingCalenders { get; set; }
    } 
}
