//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	namespace coreLogic
	{
	
    using System;
    using System.Collections.Generic;
    
    public interface IcreditMemo
    {
        long creditMemoId { get; set; }
        Nullable<long> arInvoiceId { get; set; }
        System.DateTime memoDate { get; set; }
        double totalAmountReturned { get; set; }
        double totalBalanceLeft { get; set; }
        bool approved { get; set; }
        string approvedBy { get; set; }
        bool posted { get; set; }
        Nullable<System.DateTime> postedDate { get; set; }
        int creditMemoReasonId { get; set; }
        int currencyId { get; set; }
        double totalAmountReturnedLocal { get; set; }
        double buyRate { get; set; }
        double sellRate { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        System.DateTime modified { get; set; }
        Nullable<long> arPaymentId { get; set; }
        string memoNumber { get; set; }
        long customerId { get; set; }
    
        IarInvoice arInvoice { get; set; }
        IcreditMemoReason creditMemoReason { get; set; }
        IarPayment arPayment { get; set; }
        ICollection<IcreditMemoLine> creditMemoLines { get; set; }
    } 
}
