//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	namespace coreLogic
	{
	
    using System;
    using System.Collections.Generic;
    
    public interface IinventoryTransfer
    {
        int inventoryTransferId { get; set; }
        int fromLocationId { get; set; }
        int toLocationId { get; set; }
        Nullable<System.DateTime> requisitionDate { get; set; }
        bool approved { get; set; }
        Nullable<System.DateTime> approvedDate { get; set; }
        string approver { get; set; }
        string enteredBy { get; set; }
        bool delivered { get; set; }
        Nullable<System.DateTime> deliveredDate { get; set; }
        string receivedBy { get; set; }
        bool posted { get; set; }
        Nullable<System.DateTime> postedDate { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        System.DateTime modified { get; set; }
        string postedBy { get; set; }
        string postingComments { get; set; }
        string approvalComments { get; set; }
        string deliveredBy { get; set; }
        string deliveryCosmments { get; set; }
        string deliveryComments { get; set; }
        string receiptComments { get; set; }
        Nullable<System.DateTime> receiptDate { get; set; }
    
        Ilocation location { get; set; }
        Ilocation location1 { get; set; }
        ICollection<IinventoryTransferDetail> inventoryTransferDetails { get; set; }
    } 
}
