//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	namespace coreLogic
	{
	
    using System;
    using System.Collections.Generic;
    
    public interface IinventoryTransferDetail
    {
        int inventoryTransferDetailId { get; set; }
        int inventoryTransferId { get; set; }
        long inventoryItemId { get; set; }
        double quantityTransferred { get; set; }
        int fromAccountId { get; set; }
        int toAccountId { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        System.DateTime modified { get; set; }
    
        IinventoryItem inventoryItem { get; set; }
        IinventoryTransfer inventoryTransfer { get; set; }
        ICollection<IinventoryTransferDetailLine> inventoryTransferDetailLines { get; set; }
    } 
}
