//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	namespace coreLogic
	{
	
    using System;
    using System.Collections.Generic;
    
    public interface IinventoryItem
    {
        long inventoryItemId { get; set; }
        int productId { get; set; }
        int locationId { get; set; }
        int brandId { get; set; }
        string itemNumber { get; set; }
        string inventoryItemName { get; set; }
        double unitPrice { get; set; }
        double safetyStockLevel { get; set; }
        double reorderPoint { get; set; }
        int accountId { get; set; }
        int shrinkageAccountId { get; set; }
        int inventoryMethodId { get; set; }
        int currencyId { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        System.DateTime modified { get; set; }
    
        Ibrand brand { get; set; }
        Ilocation location { get; set; }
        Iproduct product { get; set; }
        ICollection<IinventoryItemDetail> inventoryItemDetails { get; set; }
        ICollection<IinventoryTransferDetail> inventoryTransferDetails { get; set; }
        ICollection<IopenningBalance> openningBalances { get; set; }
        ICollection<Ishrinkage> shrinkages { get; set; }
    } 
}
