//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	namespace coreLogic
	{
	
    using System;
    using System.Collections.Generic;
    
    public interface IopenningBalance
    {
        long openningBalanceId { get; set; }
        long openningBalanceBatchId { get; set; }
        long inventoryItemId { get; set; }
        double quantityOnHand { get; set; }
        int productId { get; set; }
        int brandId { get; set; }
        int unitOfMeasurementId { get; set; }
        Nullable<int> drAccountId { get; set; }
        Nullable<int> crAccountId { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        System.DateTime modified { get; set; }
        string batchNumber { get; set; }
    
        IinventoryItem inventoryItem { get; set; }
        IopenningBalanceBatch openningBalanceBatch { get; set; }
        IunitOfMeasurement unitOfMeasurement { get; set; }
    } 
}
