//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

	namespace coreLogic
	{
	
    using System;
    using System.Collections.Generic;
    
    public interface Iproduct
    {
        int productId { get; set; }
        int productSubCategoryId { get; set; }
        string productCode { get; set; }
        string productName { get; set; }
        string productDescription { get; set; }
        int inventoryMethodId { get; set; }
        int unitOfMeasurementId { get; set; }
        int productMakeId { get; set; }
        int productStatusId { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        System.DateTime modified { get; set; }
    
        ICollection<IinventoryItem> inventoryItems { get; set; }
        IinventoryMethod inventoryMethod { get; set; }
        IproductMake productMake { get; set; }
        IproductStatu productStatu { get; set; }
        IproductSubCategory productSubCategory { get; set; }
        IunitOfMeasurement unitOfMeasurement { get; set; }
        ICollection<IassemblyLine> assemblyLines { get; set; }
        ICollection<IbillOfMaterial> billOfMaterials { get; set; }
        ICollection<IbillOfMaterialDetail> billOfMaterialDetails { get; set; }
        ICollection<ImanufacturingCalender> manufacturingCalenders { get; set; }
    } 
}
