//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    
    public interface Iaccts
    {
        int acct_id { get; set; }
        string acc_name { get; set; }
        string acc_num { get; set; }
        bool acc_is_active { get; set; }
        Nullable<System.DateTime> creation_date { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modification_date { get; set; }
        string last_modifier { get; set; }
        byte[] version { get; set; }
    
        Iacct_heads acct_heads { get; set; }
        Icurrencies currencies { get; set; }
        ICollection<Icusts> custs { get; set; }
        ICollection<Icusts> custs1 { get; set; }
        ICollection<Isups> sups { get; set; }
        ICollection<Isups> sups1 { get; set; }
        ICollection<Ijnl_tmp> jnl_tmp { get; set; }
        ICollection<Idef_accts> def_accts { get; set; }
        ICollection<Iacct_bals> acct_bals { get; set; }
        ICollection<Ibudget> budgets { get; set; }
        ICollection<Ibank_accts> bank_accts { get; set; }
        ICollection<Ijnl> jnl { get; set; }
    }
    
}
