//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    
    public interface Ibudget
    {
        int budgetID { get; set; }
        int acct_id { get; set; }
        System.DateTime monthEndDate { get; set; }
        double budgetAmount { get; set; }
        string creator { get; set; }
        System.DateTime creationDate { get; set; }
        string modifier { get; set; }
        Nullable<System.DateTime> modificationDate { get; set; }
        Nullable<int> cost_center_id { get; set; }
        byte[] version { get; set; }
    
        Iaccts acct { get; set; }
        Igl_ou gl_ou { get; set; }
    }
    
}
