//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    
    public interface Icountries
    {
        int country_id { get; set; }
        string country_name { get; set; }
        string nationality { get; set; }
        string country_code { get; set; }
        string abbrev { get; set; }
        Nullable<System.DateTime> creation_date { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modification_date { get; set; }
        string last_modifier { get; set; }
    
        Icurrencies currencies { get; set; }
        ICollection<Iregions> regions { get; set; }
    }
    
}
