//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    
    public interface Ijnl_tmp
    {
        int jnl_id { get; set; }
        string ref_no { get; set; }
        System.DateTime tx_date { get; set; }
        Nullable<int> acct_period { get; set; }
        string description { get; set; }
        double rate { get; set; }
        double dbt_amt { get; set; }
        double crdt_amt { get; set; }
        double frgn_dbt_amt { get; set; }
        double frgn_crdt_amt { get; set; }
        Nullable<System.DateTime> creation_date { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modification_date { get; set; }
        string last_modifier { get; set; }
        string recipient { get; set; }
        string check_no { get; set; }
        byte[] version { get; set; }
    
        Iaccts accts { get; set; }
        Icurrencies currencies { get; set; }
        Igl_ou gl_ou { get; set; }
        Ijnl_batch_tmp jnl_batch_tmp { get; set; }
    }
    
}
