//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    
    public interface IroleMenu
    {
        int roleMenuID { get; set; }
        string roleName { get; set; }
        string description { get; set; }
        string iconFile { get; set; }
        string navigateUrl { get; set; }
    
        ICollection<IroleMenuItem> roleMenuItem { get; set; }
    }
    
}
