//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    
    public interface Isups
    {
        int sup_id { get; set; }
        Nullable<int> rep_emp_id { get; set; }
        string acc_num { get; set; }
        string sup_name { get; set; }
        string contact_person { get; set; }
        string debit_terms { get; set; }
        Nullable<System.DateTime> creation_date { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modification_date { get; set; }
        string last_modifier { get; set; }
    
        Iaccts ap_accts { get; set; }
        Iaccts vat_accts { get; set; }
        Icurrencies currencies { get; set; }
        Isup_types sup_types { get; set; }
    }
    
}
