//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    
    public interface Ivw_cities
    {
        string country_name { get; set; }
        string region_name { get; set; }
        string city_name { get; set; }
        string district_name { get; set; }
        int city_id { get; set; }
        int country_id { get; set; }
        int region_id { get; set; }
        int district_id { get; set; }
    }
    
}
