//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public agent()
        {
            this.agentImages = new HashSet<agentImage>();
            this.agentAddresses = new HashSet<agentAddress>();
            this.agentDocuments = new HashSet<agentDocument>();
            this.agentEmails = new HashSet<agentEmail>();
            this.agentNextOfKins = new HashSet<agentNextOfKin>();
            this.agentPhones = new HashSet<agentPhone>();
            this.loanIncentives = new HashSet<loanIncentive>();
            this.regularSusuAccounts = new HashSet<regularSusuAccount>();
            this.susuAccounts = new HashSet<susuAccount>();
            this.loans = new HashSet<loan>();
        }
    
        public int agentID { get; set; }
        public string agentNo { get; set; }
        public string surName { get; set; }
        public string otherNames { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string sex { get; set; }
        public Nullable<int> accountTypeID { get; set; }
        public string accountNumber { get; set; }
        public string accountName { get; set; }
        public Nullable<int> bankBranchID { get; set; }
        public Nullable<int> branchID { get; set; }
    
        public virtual ICollection<agentImage> agentImages { get; set; }
        public virtual branch branch { get; set; }
        public virtual ICollection<agentAddress> agentAddresses { get; set; }
        public virtual ICollection<agentDocument> agentDocuments { get; set; }
        public virtual ICollection<agentEmail> agentEmails { get; set; }
        public virtual ICollection<agentNextOfKin> agentNextOfKins { get; set; }
        public virtual ICollection<agentPhone> agentPhones { get; set; }
        public virtual ICollection<loanIncentive> loanIncentives { get; set; }
        public virtual ICollection<regularSusuAccount> regularSusuAccounts { get; set; }
        public virtual ICollection<susuAccount> susuAccounts { get; set; }
        public virtual bankAccountType bankAccountType { get; set; }
        public virtual ICollection<loan> loans { get; set; }
    }
}
