//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowingFee
    {
        public int borrowingfeeId { get; set; }
        public int borrowingId { get; set; }
        public System.DateTime feeDate { get; set; }
        public double feeAmount { get; set; }
        public int feeTypeId { get; set; }
        public System.DateTime created { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modifier { get; set; }
    
        public virtual borrowing borrowing { get; set; }
        public virtual loanFeeType loanFeeType { get; set; }
    }
}
