//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowingType
    {
        public borrowingType()
        {
            this.borrowings = new HashSet<borrowing>();
        }
    
        public int borrowingTypeId { get; set; }
        public string borrowingTypeName { get; set; }
        public int vaultAccountId { get; set; }
        public int commissionAndFeesAccountId { get; set; }
        public int holdingAccountId { get; set; }
        public int withHoldingAccountId { get; set; }
        public int accountsPayableAccountId { get; set; }
        public int interestExpenseAccountId { get; set; }
        public int interestPayableAccountId { get; set; }
    
        public virtual ICollection<borrowing> borrowings { get; set; }
    }
}
