//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashierFundsTransfer
    {
        public int cashierFundsTransferId { get; set; }
        public int sendingCashierTillId { get; set; }
        public int receivingCashierTillId { get; set; }
        public double transferAmount { get; set; }
        public System.DateTime transferDate { get; set; }
    
        public virtual cashiersTill cashiersTill { get; set; }
        public virtual cashiersTill cashiersTill1 { get; set; }
    }
}
