//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashierTransactionWithdrawalCurrency
    {
        public int cashierTransactionWithdrawalCurrencyId { get; set; }
        public int cashierTransactionWithdrawalId { get; set; }
        public int currencyNoteId { get; set; }
        public int quantity { get; set; }
        public double total { get; set; }
        public double totalDB { get; set; }
        public double totalCD { get; set; }
        public double quantityDB { get; set; }
        public double quantityCD { get; set; }
    
        public virtual cashierTransactionWithdrawal cashierTransactionWithdrawal { get; set; }
        public virtual currencyNote currencyNote { get; set; }
    }
}
