//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkApply1
    {
        public int checkApplyId { get; set; }
        public int clientCheckDetailId { get; set; }
        public int depositId { get; set; }
        public double amountApplied { get; set; }
        public System.DateTime appliedDate { get; set; }
        public bool posted { get; set; }
        public string postedBy { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
    
        public virtual clientCheckDetail1 clientCheckDetail { get; set; }
        public virtual deposit deposit { get; set; }
    }
}
