//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientConfig
    {
        public int clientConfigId { get; set; }
        public bool admissionFeeEnabled { get; set; }
        public double admissionFeeAmount { get; set; }
    }
}
