//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientLiability
    {
        public int clientLiabilityID { get; set; }
        public int clientID { get; set; }
        public Nullable<double> amountBorrowed { get; set; }
        public Nullable<int> institutionID { get; set; }
        public string businessName { get; set; }
        public Nullable<double> outstandingBalance { get; set; }
        public Nullable<System.DateTime> repaymentDate { get; set; }
        public byte[] version { get; set; }
    
        public virtual client client { get; set; }
        public virtual institution institution { get; set; }
    }
}
