//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class collateralImage
    {
        public int collateralImageID { get; set; }
        public int loanCollateralID { get; set; }
        public int imageID { get; set; }
        public byte[] version { get; set; }
    
        public virtual loanCollateral loanCollateral { get; set; }
        public virtual image image { get; set; }
    }
}
