//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class config
    {
        public int configId { get; set; }
        public bool postInterestUnIntOnDisb { get; set; }
        public bool securityDepositEnabled { get; set; }
        public bool transactionalBankingEnabled { get; set; }
        public int loanPenaltyGracePeriodInDays { get; set; }
    }
}
