//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class depositDisInvestmentConfig
    {
        public int depositDisInvestmentConfigId { get; set; }
        public double minTenure { get; set; }
        public double maxTenure { get; set; }
        public double penaltyRate { get; set; }
    }
}
