//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class deposit
    {
        public deposit()
        {
            this.depositAdditionals = new HashSet<depositAdditional>();
            this.depositCharges = new HashSet<depositCharge>();
            this.depositInterests = new HashSet<depositInterest>();
            this.depositSchedules = new HashSet<depositSchedule>();
            this.depositSignatories = new HashSet<depositSignatory>();
            this.depositWithdrawals = new HashSet<depositWithdrawal>();
            this.depositAuthorizations = new HashSet<depositAuthorization>();
            this.depositNextOfKins = new HashSet<depositNextOfKin>();
            this.depositRateUpgrades = new HashSet<depositRateUpgrade>();
            this.depositUpgrades = new HashSet<depositUpgrade>();
            this.depositUpgrades1 = new HashSet<depositUpgrade>();
        }
    
        public int depositID { get; set; }
        public int clientID { get; set; }
        public int depositTypeID { get; set; }
        public double amountInvested { get; set; }
        public double interestAccumulated { get; set; }
        public double interestBalance { get; set; }
        public double principalBalance { get; set; }
        public double interestRate { get; set; }
        public System.DateTime firstDepositDate { get; set; }
        public int period { get; set; }
        public Nullable<System.DateTime> maturityDate { get; set; }
        public bool autoRollover { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string last_modifier { get; set; }
        public string depositNo { get; set; }
        public Nullable<System.DateTime> lastInterestDate { get; set; }
        public bool interestMethod { get; set; }
        public int interestRepaymentModeID { get; set; }
        public int principalRepaymentModeID { get; set; }
        public double principalAuthorized { get; set; }
        public double interestAuthorized { get; set; }
        public int interestCalculationScheduleID { get; set; }
        public double fxRate { get; set; }
        public int currencyID { get; set; }
        public double localAmount { get; set; }
        public double lastPrincipalFxGainLoss { get; set; }
        public double lastInterestFxGainLoss { get; set; }
        public int interestPayableAccountID { get; set; }
        public double interestExpected { get; set; }
        public byte[] version { get; set; }
        public Nullable<int> staffID { get; set; }
        public bool modern { get; set; }
        public Nullable<int> agentId { get; set; }
        public double annualInterestRate { get; set; }
        public int depositPeriodInDays { get; set; }
        public bool maturityNotificationSent { get; set; }
        public bool closed { get; set; }
    
        public virtual client client { get; set; }
        public virtual depositType depositType { get; set; }
        public virtual ICollection<depositAdditional> depositAdditionals { get; set; }
        public virtual ICollection<depositCharge> depositCharges { get; set; }
        public virtual ICollection<depositInterest> depositInterests { get; set; }
        public virtual ICollection<depositSchedule> depositSchedules { get; set; }
        public virtual ICollection<depositSignatory> depositSignatories { get; set; }
        public virtual ICollection<depositWithdrawal> depositWithdrawals { get; set; }
        public virtual ICollection<depositAuthorization> depositAuthorizations { get; set; }
        public virtual ICollection<depositNextOfKin> depositNextOfKins { get; set; }
        public virtual ICollection<depositRateUpgrade> depositRateUpgrades { get; set; }
        public virtual ICollection<depositUpgrade> depositUpgrades { get; set; }
        public virtual ICollection<depositUpgrade> depositUpgrades1 { get; set; }
    }
}
