//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class depositType
    {
        public depositType()
        {
            this.deposits = new HashSet<deposit>();
            this.depositTypeAllowedTenures = new HashSet<depositTypeAllowedTenure>();
            this.depositTypePlanRates = new HashSet<depositTypePlanRate>();
            this.depositUpgrades = new HashSet<depositUpgrade>();
            this.depositUpgrades1 = new HashSet<depositUpgrade>();
        }
    
        public int depositTypeID { get; set; }
        public string depositTypeName { get; set; }
        public double interestRate { get; set; }
        public int defaultPeriod { get; set; }
        public bool allowsInterestWithdrawal { get; set; }
        public bool allowsPrincipalWithdrawal { get; set; }
        public Nullable<int> vaultAccountID { get; set; }
        public Nullable<int> accountsPayableAccountID { get; set; }
        public Nullable<int> interestExpenseAccountID { get; set; }
        public int fxUnrealizedGainLossAccountID { get; set; }
        public int fxRealizedGainLossAccountID { get; set; }
        public int interestCalculationScheduleID { get; set; }
        public Nullable<int> chargesIncomeAccountID { get; set; }
        public Nullable<int> interestPayableAccountID { get; set; }
        public bool fixedRate { get; set; }
        public bool upgradeable { get; set; }
        public double upgradeMinimumAmount { get; set; }
        public int ordinal { get; set; }
        public bool allowAdditionalDeposit { get; set; }
        public bool isCompoundInterest { get; set; }
        public bool depositInterestUpgradeable { get; set; }
    
        public virtual ICollection<deposit> deposits { get; set; }
        public virtual ICollection<depositTypeAllowedTenure> depositTypeAllowedTenures { get; set; }
        public virtual ICollection<depositTypePlanRate> depositTypePlanRates { get; set; }
        public virtual ICollection<depositUpgrade> depositUpgrades { get; set; }
        public virtual ICollection<depositUpgrade> depositUpgrades1 { get; set; }
    }
}
