//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class depositTypePlanRate
    {
        public depositTypePlanRate()
        {
            this.depositRateUpgrades = new HashSet<depositRateUpgrade>();
        }
    
        public int depositTypePlanRateId { get; set; }
        public int depositTypeId { get; set; }
        public double minimumAmount { get; set; }
        public double maximumAmount { get; set; }
        public double interestRate { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public bool useTreasuryBillRate { get; set; }
        public bool useIncrement { get; set; }
    
        public virtual depositType depositType { get; set; }
        public virtual ICollection<depositRateUpgrade> depositRateUpgrades { get; set; }
    }
}
