//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class depositAdditional
    {
        public int depositAdditionalID { get; set; }
        public int depositID { get; set; }
        public System.DateTime depositDate { get; set; }
        public double depositAmount { get; set; }
        public double principalBalance { get; set; }
        public double interestBalance { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string last_modifier { get; set; }
        public Nullable<int> bankID { get; set; }
        public string checkNo { get; set; }
        public int modeOfPaymentID { get; set; }
        public double fxRate { get; set; }
        public double localAmount { get; set; }
        public double lastPrincipalFxGainLoss { get; set; }
        public bool posted { get; set; }
        public string naration { get; set; }
        public byte[] version { get; set; }
        public double balanceBD { get; set; }
        public Nullable<System.DateTime> lastInterestDate { get; set; }
    
        public virtual deposit deposit { get; set; }
        public virtual modeOfPayment modeOfPayment { get; set; }
    }
}
