//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class employer
    {
        public employer()
        {
            this.employeeCategories = new HashSet<employeeCategory>();
            this.employerDepartments = new HashSet<employerDepartment>();
            this.employerDirectors = new HashSet<employerDirector>();
            this.privateCompanyStaffs = new HashSet<privateCompanyStaff>();
            this.staffCategory1 = new HashSet<staffCategory1>();
        }
    
        public int employerID { get; set; }
        public Nullable<int> employmentTypeID { get; set; }
        public string employerName { get; set; }
        public Nullable<int> employerAddressID { get; set; }
        public string officeNumber { get; set; }
        public byte[] version { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<employeeCategory> employeeCategories { get; set; }
        public virtual employmentType employmentType { get; set; }
        public virtual ICollection<employerDepartment> employerDepartments { get; set; }
        public virtual ICollection<employerDirector> employerDirectors { get; set; }
        public virtual ICollection<privateCompanyStaff> privateCompanyStaffs { get; set; }
        public virtual ICollection<staffCategory1> staffCategory1 { get; set; }
    }
}
