//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class employmentStatu
    {
        public employmentStatu()
        {
            this.staffs = new HashSet<staff>();
        }
    
        public int employmentStatusID { get; set; }
        public string employmentStatusName { get; set; }
    
        public virtual ICollection<staff> staffs { get; set; }
    }
}
