//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class holidayType
    {
        public holidayType()
        {
            this.publicHolidays = new HashSet<publicHoliday>();
        }
    
        public int holidayTypeID { get; set; }
        public string holidayTypeName { get; set; }
    
        public virtual ICollection<publicHoliday> publicHolidays { get; set; }
    }
}
