//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public image()
        {
            this.staffImages = new HashSet<staffImage>();
            this.addressImages = new HashSet<addressImage>();
            this.agentImages = new HashSet<agentImage>();
            this.agentNextOfKins = new HashSet<agentNextOfKin>();
            this.clientImages = new HashSet<clientImage>();
            this.collateralImages = new HashSet<collateralImage>();
            this.depositSignatories = new HashSet<depositSignatory>();
            this.investmentSignatories = new HashSet<investmentSignatory>();
            this.loanGurantors = new HashSet<loanGurantor>();
            this.nextOfKins = new HashSet<nextOfKin>();
            this.savingSignatories = new HashSet<savingSignatory>();
            this.smeDirectors = new HashSet<smeDirector>();
            this.assetImages = new HashSet<assetImage>();
            this.employerDirectors = new HashSet<employerDirector>();
        }
    
        public int imageID { get; set; }
        public string description { get; set; }
        public byte[] image1 { get; set; }
        public string content_type { get; set; }
        public byte[] version { get; set; }
    
        public virtual ICollection<staffImage> staffImages { get; set; }
        public virtual ICollection<addressImage> addressImages { get; set; }
        public virtual ICollection<agentImage> agentImages { get; set; }
        public virtual ICollection<agentNextOfKin> agentNextOfKins { get; set; }
        public virtual ICollection<clientImage> clientImages { get; set; }
        public virtual ICollection<collateralImage> collateralImages { get; set; }
        public virtual ICollection<depositSignatory> depositSignatories { get; set; }
        public virtual ICollection<investmentSignatory> investmentSignatories { get; set; }
        public virtual ICollection<loanGurantor> loanGurantors { get; set; }
        public virtual ICollection<nextOfKin> nextOfKins { get; set; }
        public virtual ICollection<savingSignatory> savingSignatories { get; set; }
        public virtual ICollection<smeDirector> smeDirectors { get; set; }
        public virtual ICollection<assetImage> assetImages { get; set; }
        public virtual ICollection<employerDirector> employerDirectors { get; set; }
    }
}
