//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class institution
    {
        public institution()
        {
            this.clientLiabilities = new HashSet<clientLiability>();
        }
    
        public int institutionID { get; set; }
        public string institutionName { get; set; }
    
        public virtual ICollection<clientLiability> clientLiabilities { get; set; }
    }
}
