//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class investmentSystemDateChange
    {
        public int investmentSystemDateChangeId { get; set; }
        public byte systemDateID { get; set; }
        public Nullable<System.DateTime> changeFrom { get; set; }
        public Nullable<System.DateTime> changeTo { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string creator { get; set; }
    
        public virtual systemDate systemDate { get; set; }
    }
}
