//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class levelBenefitsInKind
    {
        public int levelBenefitsInKindID { get; set; }
        public int levelID { get; set; }
        public int benefitsInKindID { get; set; }
    
        public virtual level level { get; set; }
    }
}
