//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanClosure
    {
        public int loanClosureId { get; set; }
        public int loanId { get; set; }
        public Nullable<System.DateTime> closureDate { get; set; }
        public Nullable<System.DateTime> requestedClosureDate { get; set; }
        public Nullable<bool> approved { get; set; }
        public string approvalComments { get; set; }
        public bool posted { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public string approvedBy { get; set; }
        public string requestedBy { get; set; }
        public Nullable<System.DateTime> postingDate { get; set; }
        public string postedBy { get; set; }
        public int loanClosureReasonId { get; set; }
        public string closureComments { get; set; }
        public double principalBalanceAtClosure { get; set; }
        public double interestBalanceAtClosure { get; set; }
        public double feesAndChargesAtClosure { get; set; }
    
        public virtual loanClosureReason loanClosureReason { get; set; }
        public virtual loan loan { get; set; }
    }
}
