//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanApproval
    {
        public int loanApprovalId { get; set; }
        public int loanId { get; set; }
        public double amountApproved { get; set; }
        public System.DateTime approvalDate { get; set; }
        public string approvalAction { get; set; }
        public string approvedBy { get; set; }
        public string approvalComment { get; set; }
        public int approvalStageId { get; set; }
        public System.DateTime created { get; set; }
        public int approvedTenure { get; set; }
        public string creator { get; set; }
    
        public virtual loanApprovalStage loanApprovalStage { get; set; }
        public virtual loan loan { get; set; }
    }
}
