//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanApprovalStage
    {
        public loanApprovalStage()
        {
            this.loanApprovals = new HashSet<loanApproval>();
            this.loanApprovalStageOfficers = new HashSet<loanApprovalStageOfficer>();
        }
    
        public int loanApprovalStageId { get; set; }
        public int loanTypeId { get; set; }
        public string name { get; set; }
        public bool isMandatory { get; set; }
        public string ordinal { get; set; }
    
        public virtual ICollection<loanApproval> loanApprovals { get; set; }
        public virtual loanType loanType { get; set; }
        public virtual ICollection<loanApprovalStageOfficer> loanApprovalStageOfficers { get; set; }
    }
}
