//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanFee
    {
        public int loanFeeID { get; set; }
        public int loanID { get; set; }
        public System.DateTime feeDate { get; set; }
        public double feeAmount { get; set; }
        public int feeTypeID { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string last_modifier { get; set; }
        public byte[] version { get; set; }
    
        public virtual loanFeeType loanFeeType { get; set; }
        public virtual loan loan { get; set; }
    }
}
