//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanPenaltyDisable
    {
        public int loanPenaltyDisableId { get; set; }
        public int loanId { get; set; }
        public System.DateTime disabledDate { get; set; }
        public string disabledBy { get; set; }
    
        public virtual loan loan { get; set; }
    }
}
