//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanType
    {
        public loanType()
        {
            this.insuranceSetups = new HashSet<insuranceSetup>();
            this.loanApprovalStages = new HashSet<loanApprovalStage>();
            this.loans = new HashSet<loan>();
        }
    
        public int loanTypeID { get; set; }
        public string loanTypeName { get; set; }
        public int vaultAccountID { get; set; }
        public int bankAccountID { get; set; }
        public int writeOffAccountID { get; set; }
        public int unearnedInterestAccountID { get; set; }
        public int interestIncomeAccountID { get; set; }
        public int unpaidCommissionAccountID { get; set; }
        public int commissionAndFeesAccountID { get; set; }
        public int accountsReceivableAccountID { get; set; }
        public int unearnedExtraChargesAccountID { get; set; }
        public string tagPrefix { get; set; }
        public int incentiveAccountID { get; set; }
        public int holdingAccountID { get; set; }
        public int refundAccountID { get; set; }
        public int withHoldingAccountID { get; set; }
        public int apIncentiveAccountID { get; set; }
        public int apCommissionAccountID { get; set; }
        public int commissionAccountID { get; set; }
        public int provisionExpenseAccountID { get; set; }
        public int provisionsAccountID { get; set; }
    
        public virtual ICollection<insuranceSetup> insuranceSetups { get; set; }
        public virtual ICollection<loanApprovalStage> loanApprovalStages { get; set; }
        public virtual ICollection<loan> loans { get; set; }
    }
}
