//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanCheckList
    {
        public int loanCheckListID { get; set; }
        public Nullable<int> categoryCheckListID { get; set; }
        public int loanID { get; set; }
        public bool passed { get; set; }
        public string comments { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public byte[] version { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modifier { get; set; }
    
        public virtual categoryCheckList categoryCheckList { get; set; }
        public virtual loan loan { get; set; }
    }
}
