//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanFeeType
    {
        public loanFeeType()
        {
            this.loanFees = new HashSet<loanFee>();
            this.borrowingFees = new HashSet<borrowingFee>();
        }
    
        public int feeTypeID { get; set; }
        public string feeTypeName { get; set; }
    
        public virtual ICollection<loanFee> loanFees { get; set; }
        public virtual ICollection<borrowingFee> borrowingFees { get; set; }
    }
}
