//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class payMasterLoan
    {
        public int payMasterLoanID { get; set; }
        public int payMasterID { get; set; }
        public int staffLoanID { get; set; }
        public double amountDeducted { get; set; }
        public double principalDeducted { get; set; }
        public double interestDeducted { get; set; }
        public string description { get; set; }
        public byte[] version { get; set; }
    
        public virtual payMaster payMaster { get; set; }
        public virtual staffLoan staffLoan { get; set; }
    }
}
