//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class productCode
    {
        public int productCodeID { get; set; }
        public string savingsAccountCode { get; set; }
        public string loanAccountCode { get; set; }
        public string depositAccountCode { get; set; }
        public string groupSusuAccountCode { get; set; }
        public string normalSusuAccountCode { get; set; }
        public string investmentAccountCode { get; set; }
    }
}
