//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicHoliday
    {
        public int publicHolidayID { get; set; }
        public System.DateTime date { get; set; }
        public int yearID { get; set; }
        public int holidayTypeID { get; set; }
    
        public virtual holidayType holidayType { get; set; }
        public virtual year year { get; set; }
    }
}
