//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class savingPlan
    {
        public int savingPlanID { get; set; }
        public int savingID { get; set; }
        public System.DateTime plannedDate { get; set; }
        public double plannedAmount { get; set; }
        public bool deposited { get; set; }
        public string creator { get; set; }
        public System.DateTime creationDate { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public double amountDeposited { get; set; }
    
        public virtual saving saving { get; set; }
    }
}
