//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class savingNextOfKin
    {
        public int savingNextOfKinId { get; set; }
        public int savingId { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string otherNames { get; set; }
        public string surName { get; set; }
        public string relationshipType { get; set; }
        public int idTypeId { get; set; }
        public string idNumber { get; set; }
        public double percentageAllocated { get; set; }
        public byte[] picture { get; set; }
        public string phoneNumber { get; set; }
    
        public virtual idNoType idNoType { get; set; }
        public virtual saving saving { get; set; }
    }
}
