//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialDayType1
    {
        public SpecialDayType1()
        {
            this.SpecialDays = new HashSet<SpecialDay1>();
        }
    
        public short specialDayTypeId { get; set; }
        public string specialDayTypeName { get; set; }
        public string specialDayTypeCode { get; set; }
    
        public virtual ICollection<SpecialDay1> SpecialDays { get; set; }
    }
}
