//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffManager
    {
        public int staffManagerID { get; set; }
        public int staffID { get; set; }
        public Nullable<int> managerStaffID { get; set; }
        public int levelID { get; set; }
        public Nullable<int> levelNotchID { get; set; }
        public Nullable<System.DateTime> employmentStartDate { get; set; }
        public Nullable<System.DateTime> employmentStopDate { get; set; }
        public byte[] version { get; set; }
    
        public virtual level level { get; set; }
        public virtual levelNotch levelNotch { get; set; }
        public virtual staff staff { get; set; }
        public virtual staff staff1 { get; set; }
    }
}
