//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemDate
    {
        public systemDate()
        {
            this.accountsSystemDateChanges = new HashSet<accountsSystemDateChange>();
            this.depositSystemDateChanges = new HashSet<depositSystemDateChange>();
            this.savingSystemDateChanges = new HashSet<savingSystemDateChange>();
            this.susuSystemDateChanges = new HashSet<susuSystemDateChange>();
            this.creditUnionSystemDateChanges = new HashSet<creditUnionSystemDateChange>();
            this.investmentSystemDateChanges = new HashSet<investmentSystemDateChange>();
            this.loanSystemDateChanges = new HashSet<loanSystemDateChange>();
        }
    
        public byte systemDateID { get; set; }
        public Nullable<System.DateTime> loanSystemDate { get; set; }
        public Nullable<System.DateTime> savingSystemDate { get; set; }
        public Nullable<System.DateTime> depositSystemDate { get; set; }
        public Nullable<System.DateTime> investmentSystemDate { get; set; }
        public Nullable<System.DateTime> susuSystemDate { get; set; }
        public Nullable<System.DateTime> creditUnionSystemDate { get; set; }
        public Nullable<System.DateTime> accountsSystemDate { get; set; }
        public bool useSystemDates { get; set; }
    
        public virtual ICollection<accountsSystemDateChange> accountsSystemDateChanges { get; set; }
        public virtual ICollection<depositSystemDateChange> depositSystemDateChanges { get; set; }
        public virtual ICollection<savingSystemDateChange> savingSystemDateChanges { get; set; }
        public virtual ICollection<susuSystemDateChange> susuSystemDateChanges { get; set; }
        public virtual ICollection<creditUnionSystemDateChange> creditUnionSystemDateChanges { get; set; }
        public virtual ICollection<investmentSystemDateChange> investmentSystemDateChanges { get; set; }
        public virtual ICollection<loanSystemDateChange> loanSystemDateChanges { get; set; }
    }
}
