//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxTable
    {
        public int taxTableID { get; set; }
        public double amount { get; set; }
        public double taxPercent { get; set; }
        public int sortOrder { get; set; }
    }
}
