//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class chart_of_accounts
    {
        public string acc_num { get; set; }
        public string acc_name { get; set; }
        public string major_name { get; set; }
        public string major_symbol { get; set; }
        public string minor_name { get; set; }
        public string minor_symbol { get; set; }
        public string cat_name { get; set; }
        public string head_name1 { get; set; }
        public string head_name2 { get; set; }
        public string head_name3 { get; set; }
        public string head_name4 { get; set; }
        public string head_nam5 { get; set; }
        public string head_name6 { get; set; }
        public string head_name7 { get; set; }
        public byte cat_code { get; set; }
    }
}
