//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_v
    {
        public string item { get; set; }
        public string v_type { get; set; }
        public string type { get; set; }
        public string batch_no { get; set; }
        public string major_name { get; set; }
        public string minor_name { get; set; }
        public string major_symbol { get; set; }
        public string minor_symbol { get; set; }
        public decimal rate { get; set; }
        public decimal with_rate { get; set; }
        public decimal vat_rate { get; set; }
        public decimal nhil_rate { get; set; }
        public decimal with_amt { get; set; }
        public decimal vat_amt { get; set; }
        public decimal nhil_amt { get; set; }
        public string check_no { get; set; }
        public string invoice_no { get; set; }
        public bool is_vat { get; set; }
        public bool is_nhil { get; set; }
        public bool is_withheld { get; set; }
        public bool posted { get; set; }
        public string comp_name { get; set; }
        public string bank_acc_name { get; set; }
        public string bank_acc_num { get; set; }
        public string with_acc_name { get; set; }
        public string with_acc_num { get; set; }
        public string dtl_acc_name { get; set; }
        public string dtl_acc_num { get; set; }
        public string ref_no { get; set; }
        public System.DateTime tx_date { get; set; }
        public string ou_name { get; set; }
        public string description { get; set; }
        public decimal tot_amount { get; set; }
        public decimal amount { get; set; }
    }
}
