//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAlert
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string alert { get; set; }
        public string staffName { get; set; }
        public string userName { get; set; }
        public string AlertType { get; set; }
        public string url { get; set; }
        public int clientID { get; set; }
    }
}
