//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwApprovedUndisbured
    {
        public string clientName { get; set; }
        public string accountNumber { get; set; }
        public int clientID { get; set; }
        public string categoryName { get; set; }
        public double amountDisbursed { get; set; }
        public string loanTypeName { get; set; }
        public double amountApproved { get; set; }
        public System.DateTime finalApprovalDate { get; set; }
        public System.DateTime applicationDate { get; set; }
        public System.DateTime disbursementDate { get; set; }
        public string collateralType { get; set; }
        public double collateralValue { get; set; }
        public double interestBalance { get; set; }
        public double principalBalance { get; set; }
        public double interestPayment { get; set; }
        public double principalPayment { get; set; }
        public int daysDue { get; set; }
        public double processingFee { get; set; }
    }
}
