//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDepositWithdrawal
    {
        public int depositID { get; set; }
        public int clientID { get; set; }
        public string clientName { get; set; }
        public System.DateTime withdrawalDate { get; set; }
        public string accountNumber { get; set; }
        public string branchName { get; set; }
        public System.DateTime creation_date { get; set; }
        public string creator { get; set; }
        public double amountWithdrawn { get; set; }
        public int depositWithdrawalID { get; set; }
        public double interestWithdrawal { get; set; }
        public double principalWithdrawal { get; set; }
        public string depositTypeName { get; set; }
        public int depositTypeID { get; set; }
        public double interestRate { get; set; }
        public double principalBalance { get; set; }
        public double interestBalance { get; set; }
        public double interestExpected { get; set; }
        public string modeOfPaymentName { get; set; }
        public string depositNo { get; set; }
        public string naration { get; set; }
        public bool posted { get; set; }
        public string agentName { get; set; }
    }
}
