//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInvoiceLoanMaster
    {
        public int clientID { get; set; }
        public string clientName { get; set; }
        public string accountNumber { get; set; }
        public string addressLine1 { get; set; }
        public string workPhone { get; set; }
        public string mobilePhone { get; set; }
        public string homePhone { get; set; }
        public string addressLine2 { get; set; }
        public string cityTown { get; set; }
        public int supplierID { get; set; }
        public string supplierName { get; set; }
        public double ceilRate { get; set; }
        public bool approved { get; set; }
        public bool disbursed { get; set; }
        public double checkAmount { get; set; }
        public string approvedBy { get; set; }
        public System.DateTime approvalDate { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public double invoiceAmount { get; set; }
        public double withHoldingTax { get; set; }
        public double amountDisbursed { get; set; }
        public double interestAmount { get; set; }
        public double processingFee { get; set; }
        public double proposedAmount { get; set; }
        public double rate { get; set; }
        public string invoiceDescription { get; set; }
        public string invoiceNo { get; set; }
        public int invoiceLoanMasterID { get; set; }
        public int invoiceLoanID { get; set; }
        public string loanNo { get; set; }
        public System.DateTime disbursementDate { get; set; }
        public double amountPaid { get; set; }
        public double feePaid { get; set; }
        public double penaltyPaid { get; set; }
        public double penaltyAmount { get; set; }
        public string paymentDate { get; set; }
    }
}
