//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLoanTenor2
    {
        public string tenor { get; set; }
        public double ratePersonal { get; set; }
        public double rateGroup { get; set; }
        public double rateBusiness { get; set; }
        public double rateOther { get; set; }
        public int id { get; set; }
    }
}
