//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLoanAgreement
    {
        public int clientID { get; set; }
        public string clientName { get; set; }
        public string accountNumber { get; set; }
        public int loanID { get; set; }
        public string loanNo { get; set; }
        public System.DateTime disbursementDate { get; set; }
        public System.DateTime finalApprovalDate { get; set; }
        public System.DateTime applicationDate { get; set; }
        public double amountDisbursed { get; set; }
        public double amountApproved { get; set; }
        public double amountRequested { get; set; }
        public int loanTypeID { get; set; }
        public string loanTypeName { get; set; }
        public double interestRate { get; set; }
        public double loanTenure { get; set; }
        public double principalPayment { get; set; }
        public double interestPayment { get; set; }
        public string collateralType { get; set; }
        public double collateralValue { get; set; }
        public string workPhone { get; set; }
        public string mobilePhone { get; set; }
        public string homePhone { get; set; }
        public string phyAddr1 { get; set; }
        public string phyAddr2 { get; set; }
        public string phyCity { get; set; }
        public string mailAddr1 { get; set; }
        public string mailAddr2 { get; set; }
        public string mailCity { get; set; }
        public Nullable<long> rowNum { get; set; }
        public double processingFee { get; set; }
    }
}
