//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class momoServiceCharge
    {
        public int serviceChargeID { get; set; }
        public int serviceID { get; set; }
        public double minTranAmount { get; set; }
        public double maxTranAmount { get; set; }
        public double chargesValue { get; set; }
        public bool isPercent { get; set; }
    
        public virtual momoService momoService { get; set; }
    }
}
