//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class momoProvider
    {
        public momoProvider()
        {
            this.momoWallets = new HashSet<momoWallet>();
            this.momoServices = new HashSet<momoService>();
        }
    
        public int providerID { get; set; }
        public string providerFullName { get; set; }
        public string providerShortName { get; set; }
        public string momoProductName { get; set; }
    
        public virtual ICollection<momoWallet> momoWallets { get; set; }
        public virtual ICollection<momoService> momoServices { get; set; }
    }
}
