//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IwalletLoading
    {
        long walletLoadingID { get; set; }
        int walletID { get; set; }
        int modeOfPaymentID { get; set; }
        Nullable<int> bankID { get; set; }
        System.DateTime loadingDate { get; set; }
        double amountLoaded { get; set; }
        double balanceAfter { get; set; }
        string enteredBy { get; set; }
        System.DateTime entryDate { get; set; }
        bool posted { get; set; }
        string postedBy { get; set; }
        Nullable<System.DateTime> postingDate { get; set; }
        byte[] version { get; set; }
    
        ImomoWallet momoWallet { get; set; }
    }
     
}
