//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class accessLevel
    {
        public accessLevel()
        {
            this.users = new HashSet<users>();
        }
    
        public byte accessLevelID { get; set; }
        public string accessLevelName { get; set; }
        public double approvalLimit { get; set; }
        public double withdrawalLimit { get; set; }
        public double disbursementLimit { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
