//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_login_attempts
    {
        public long user_login_attempt_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string ip_address { get; set; }
        public System.DateTime login_attempt_date { get; set; }
        public bool was_successfull { get; set; }
        public System.DateTime creation_date { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string last_modifier { get; set; }
    }
}
