//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class webAppEmp
    {
        public int webAppID { get; set; }
        public Nullable<int> employerID { get; set; }
        public Nullable<int> departmentID { get; set; }
        public string authOfficerName { get; set; }
        public string authOfficerPosition { get; set; }
        public string authOfficerPhone { get; set; }
        public Nullable<int> contractTypeID { get; set; }
    
        public virtual webApp webApp { get; set; }
    }
}
