//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class webAppPhoto
    {
        public int webAppID { get; set; }
        public byte[] photo { get; set; }
    
        public virtual webApp webApp { get; set; }
    }
}
