//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coreSecurityEntities : DbContext, IcoreSecurityEntities
    {
        public coreSecurityEntities()
            : base("name=coreSecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<roles> roles { get; set; }
        public virtual IDbSet<user_roles> user_roles { get; set; }
        public virtual IDbSet<users> users { get; set; }
        public virtual IDbSet<user_login_attempts> user_login_attempts { get; set; }
        public virtual IDbSet<modules> modules { get; set; }
        public virtual IDbSet<perms> perms { get; set; }
        public virtual IDbSet<role_perms> role_perms { get; set; }
        public virtual IDbSet<user_perms> user_perms { get; set; }
        public virtual IDbSet<cuser> cusers { get; set; }
        public virtual IDbSet<userAudit> userAudits { get; set; }
        public virtual IDbSet<webApp> webApps { get; set; }
        public virtual IDbSet<webAppBank> webAppBanks { get; set; }
        public virtual IDbSet<webAppContact> webAppContacts { get; set; }
        public virtual IDbSet<webAppEmp> webAppEmps { get; set; }
        public virtual IDbSet<webAppEmp2> webAppEmp2 { get; set; }
        public virtual IDbSet<webAppID> webAppIDs { get; set; }
        public virtual IDbSet<webAppMailAddr> webAppMailAddrs { get; set; }
        public virtual IDbSet<webAppPhoto> webAppPhotoes { get; set; }
        public virtual IDbSet<webAppPhyAddr> webAppPhyAddrs { get; set; }
        public virtual IDbSet<webAppSalary> webAppSalaries { get; set; }
        public virtual IDbSet<userError> userErrors { get; set; }
        public virtual IDbSet<authToken> authTokens { get; set; }
        public virtual IDbSet<accessLevel> accessLevels { get; set; }
        public virtual IDbSet<kerbero> kerberos { get; set; }
    }
}
