//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class momoModelsConnectionString : DbContext, ImomoModelsConnectionString
    {
        public momoModelsConnectionString()
            : base("name=momoModelsConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<momoClient> momoClients { get; set; }
        public virtual IDbSet<momoProvider> momoProviders { get; set; }
        public virtual IDbSet<momoService> momoServices { get; set; }
        public virtual IDbSet<momoServiceCharge> momoServiceCharges { get; set; }
        public virtual IDbSet<momoTransaction> momoTransactions { get; set; }
        public virtual IDbSet<momoWallet> momoWallets { get; set; }
        public virtual IDbSet<walletCashup> walletCashups { get; set; }
        public virtual IDbSet<walletLoading> walletLoadings { get; set; }
    }
}
