//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IagentEmail
    {
        int agentEmailID { get; set; }
        int agentID { get; set; }
        Nullable<int> emailID { get; set; }
        Nullable<int> emailTypeID { get; set; }
    
        Iagent agent { get; set; }
        Iemail email { get; set; }
    } 
    
}
