//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
     // Condition: ^[^v].*Type$
    public interface IallowanceType
    {
        int allowanceTypeID { get; set; }
        string alllowanceTypeName { get; set; }
        bool isPercent { get; set; }
        double amount { get; set; }
        bool isTaxable { get; set; }
        double taxPercent { get; set; }
        bool addToBasicAndTax { get; set; }
    
        ICollection<IlevelAllowance> levelAllowances { get; set; }
        ICollection<IpayMasterAllowance> payMasterAllowances { get; set; }
        ICollection<IshiftAllowance> shiftAllowances { get; set; }
        ICollection<IstaffAllowance> staffAllowances { get; set; }
    } 
    
}
