//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IassetSubCategory
    {
        int assetSubCategoryID { get; set; }
        string assetSubCategoryName { get; set; }
        int assetCategoryID { get; set; }
    
        ICollection<Iasset> assets { get; set; }
        IassetCategory assetCategory { get; set; }
    } 
    
}
