//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IassetCategory
    {
        int assetCategoryID { get; set; }
        string assetCategoryName { get; set; }
        int depreciationMethod { get; set; }
        Nullable<int> depreciationAccountID { get; set; }
        Nullable<int> accumulatedDepreciationAccountID { get; set; }
    
        ICollection<IassetSubCategory> assetSubCategories { get; set; }
    } 
    
}
