//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IborrowingRepayment
    {
        int borrowingRepaymentId { get; set; }
        int borrowingId { get; set; }
        int modeOfPaymentId { get; set; }
        int repaymentTypeId { get; set; }
        System.DateTime repayementDate { get; set; }
        double amountPaid { get; set; }
        double interestPaid { get; set; }
        double principalPaid { get; set; }
        double feePaid { get; set; }
        double penaltyPaid { get; set; }
        double commissionPaid { get; set; }
        string checkNo { get; set; }
        Nullable<int> bankId { get; set; }
        System.DateTime created { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modified { get; set; }
        string modifier { get; set; }
    
        Iborrowing borrowing { get; set; }
        ImodeOfPayment modeOfPayment { get; set; }
        IrepaymentType repaymentType { get; set; }
    } 
    
}
