//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
     // Condition: ^[^v].*Type$
    public interface IborrowingType
    {
        int borrowingTypeId { get; set; }
        string borrowingTypeName { get; set; }
        int vaultAccountId { get; set; }
        int commissionAndFeesAccountId { get; set; }
        int holdingAccountId { get; set; }
        int withHoldingAccountId { get; set; }
        int accountsPayableAccountId { get; set; }
        int interestExpenseAccountId { get; set; }
        int interestPayableAccountId { get; set; }
    
        ICollection<Iborrowing> borrowings { get; set; }
    } 
    
}
