//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IcashierTransactionWithdrawal
    {
        int cashierTransactionWithdrawalId { get; set; }
        System.DateTime receiptDate { get; set; }
        int transactionId { get; set; }
        int transactionTypeId { get; set; }
        double totalReceiptAmount { get; set; }
        int cashierTillId { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        Nullable<System.DateTime> modified { get; set; }
        double balanceCD { get; set; }
        double balanceBD { get; set; }
    
        IcashiersTill cashiersTill { get; set; }
        ItransactionType transactionType { get; set; }
        ICollection<IcashierTransactionWithdrawalCurrency> cashierTransactionWithdrawalCurrencies { get; set; }
    } 
    
}
