//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IclientAddress
    {
        int clientAddressID { get; set; }
        int clientID { get; set; }
        Nullable<int> addressID { get; set; }
        Nullable<int> addressTypeID { get; set; }
        byte[] version { get; set; }
    
        Iaddress address { get; set; }
        Iclient client { get; set; }
    } 
    
}
