//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IclientInvestmentReceiptDetail
    {
        int clientInvestmentReceiptDetailId { get; set; }
        int clientInvestmentReceiptId { get; set; }
        double amountReceived { get; set; }
        string receivedBy { get; set; }
        System.DateTime receiptDate { get; set; }
        bool invested { get; set; }
        string investedBy { get; set; }
        Nullable<System.DateTime> investedDate { get; set; }
        string modifier { get; set; }
        Nullable<System.DateTime> modified { get; set; }
        int paymentModeId { get; set; }
        System.DateTime created { get; set; }
        string chequeNumber { get; set; }
        Nullable<int> bankId { get; set; }
    
        IclientInvestmentReceipt clientInvestmentReceipt { get; set; }
        ImodeOfPayment modeOfPayment { get; set; }
    } 
    
}
