//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IclientEmail
    {
        int clientEmailID { get; set; }
        int clientID { get; set; }
        Nullable<int> emailID { get; set; }
        Nullable<int> emailTypeID { get; set; }
        byte[] version { get; set; }
    
        Iclient client { get; set; }
        Iemail email { get; set; }
    } 
    
}
