//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IclientConfig
    {
        int clientConfigId { get; set; }
        bool admissionFeeEnabled { get; set; }
        double admissionFeeAmount { get; set; }
    } 
    
}
