//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface Icollection
    {
        int collectionID { get; set; }
        int loanProductID { get; set; }
        int month { get; set; }
        double collection1 { get; set; }
    
        IloanProduct loanProduct { get; set; }
    } 
    
}
