//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IdepositConfig
    {
        int depositConfigId { get; set; }
        bool interestWithDrawBySav { get; set; }
        double disInvestmentRate { get; set; }
        bool clientDepositBySav { get; set; }
        int staffDepositInterestRate { get; set; }
    } 
    
}
