//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IdepositTypeAllowedTenure
    {
        int depositTypeAllowedTenureId { get; set; }
        int depositTypeId { get; set; }
        int tenureTypeId { get; set; }
        int minTenure { get; set; }
        int maxTenure { get; set; }
    
        IdepositType depositType { get; set; }
        ItenureType tenureType { get; set; }
    } 
    
}
