//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IdepositDisInvestmentConfig
    {
        int depositDisInvestmentConfigId { get; set; }
        double minTenure { get; set; }
        double maxTenure { get; set; }
        double penaltyRate { get; set; }
    } 
    
}
