//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IemployeeDepartment
    {
        int employeeDepartmentId { get; set; }
        string dapartmentName { get; set; }
        string creator { get; set; }
        System.DateTime created { get; set; }
        string modifier { get; set; }
        Nullable<System.DateTime> modified { get; set; }
    
        ICollection<IprivateCompanyStaffVerification> privateCompanyStaffVerifications { get; set; }
    } 
    
}
