//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IinvoiceLoanConfig
    {
        int invoiceLoanConfigID { get; set; }
        int clientID { get; set; }
        Nullable<int> supplierID { get; set; }
        double ceilRate { get; set; }
        double standardInterestrate { get; set; }
        double standardProcessingFeerate { get; set; }
        byte[] version { get; set; }
        double maximumExposure { get; set; }
        bool allowPODisbursement { get; set; }
    
        Iclient client { get; set; }
        Isupplier supplier { get; set; }
    } 
    
}
