//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
     // Condition: ^[^v].*Type$
    public interface IleaveType
    {
        int leaveTypeID { get; set; }
        string leaveTypeName { get; set; }
    
        ICollection<IlevelLeave> levelLeaves { get; set; }
        ICollection<IstaffLeave> staffLeaves { get; set; }
    } 
    
}
