//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface Iln_type
    {
        int ln_type_id { get; set; }
        string ln_type_name { get; set; }
        double def_rate { get; set; }
        string def_rate_id { get; set; }
        int def_duration { get; set; }
        string def_duration_id { get; set; }
        bool req_approv { get; set; }
        Nullable<System.DateTime> creation_date { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modification_date { get; set; }
        string last_modifier { get; set; }
    
        Idur_type dur_type { get; set; }
    } 
    
}
