//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IloanTranch
    {
        int loanTranchID { get; set; }
        int loanID { get; set; }
        double amountDisbursed { get; set; }
        System.DateTime disbursementDate { get; set; }
        int modeOfPaymentID { get; set; }
        Nullable<System.DateTime> creation_date { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modification_date { get; set; }
        string last_modifier { get; set; }
        string checkNumber { get; set; }
        Nullable<int> bankID { get; set; }
        byte[] version { get; set; }
    
        ImodeOfPayment modeOfPayment { get; set; }
        Iloan loan { get; set; }
    } 
    
}
