//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IloanPenaltyDisable
    {
        int loanPenaltyDisableId { get; set; }
        int loanId { get; set; }
        System.DateTime disabledDate { get; set; }
        string disabledBy { get; set; }
    
        Iloan loan { get; set; }
    } 
    
}
