//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IloanCollateral
    {
        int loanCollateralID { get; set; }
        int loanID { get; set; }
        int collateralTypeID { get; set; }
        double fairValue { get; set; }
        Nullable<System.DateTime> creation_date { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modification_date { get; set; }
        string last_modifier { get; set; }
        string legalOwner { get; set; }
        string collateralDescription { get; set; }
        byte[] version { get; set; }
    
        ICollection<IcollateralImage> collateralImages { get; set; }
        IcollateralType collateralType { get; set; }
        Iloan loan { get; set; }
    } 
    
}
