//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IloanFinancial
    {
        int loanFinancialID { get; set; }
        int loanID { get; set; }
        int financialTypeID { get; set; }
        double revenue { get; set; }
        double expenses { get; set; }
        double otherCosts { get; set; }
        Nullable<int> frequencyID { get; set; }
        byte[] version { get; set; }
    
        IfinancialType financialType { get; set; }
        IrepaymentMode repaymentMode { get; set; }
        Iloan loan { get; set; }
    } 
    
}
