//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IloanCheckList
    {
        int loanCheckListID { get; set; }
        Nullable<int> categoryCheckListID { get; set; }
        int loanID { get; set; }
        bool passed { get; set; }
        string comments { get; set; }
        string description { get; set; }
        Nullable<System.DateTime> creationDate { get; set; }
        byte[] version { get; set; }
        Nullable<System.DateTime> modified { get; set; }
        string modifier { get; set; }
    
        IcategoryCheckList categoryCheckList { get; set; }
        Iloan loan { get; set; }
    } 
    
}
