//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IperformanceScore
    {
        int performanceScoreID { get; set; }
        string performanceScoreName { get; set; }
        double scoreValue { get; set; }
    
        ICollection<IperformanceAppraisalScore> performanceAppraisalScores { get; set; }
        ICollection<IperformanceContractTarget> performanceContractTargets { get; set; }
    } 
    
}
