//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IpublicHoliday
    {
        int publicHolidayID { get; set; }
        System.DateTime date { get; set; }
        int yearID { get; set; }
        int holidayTypeID { get; set; }
    
        IholidayType holidayType { get; set; }
        Iyear year { get; set; }
    } 
    
}
