//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IregularSusuWithdrawal
    {
        int regularSusuWithdrawalId { get; set; }
        int regularSusuAccountId { get; set; }
        System.DateTime withdrawalDate { get; set; }
        double balance { get; set; }
        double amount { get; set; }
        string narration { get; set; }
    
        IregularSusuAccount regularSusuAccount { get; set; }
    } 
    
}
