//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IrepaymentSchedule
    {
        int repaymentScheduleID { get; set; }
        int loanID { get; set; }
        System.DateTime repaymentDate { get; set; }
        double interestPayment { get; set; }
        double principalPayment { get; set; }
        double balanceBF { get; set; }
        double balanceCD { get; set; }
        double interestBalance { get; set; }
        double principalBalance { get; set; }
        Nullable<System.DateTime> creation_date { get; set; }
        string creator { get; set; }
        Nullable<System.DateTime> modification_date { get; set; }
        string last_modifier { get; set; }
        double proposedInterestWriteOff { get; set; }
        double interestWritenOff { get; set; }
        bool edited { get; set; }
        double origInterestPayment { get; set; }
        double additionalInterest { get; set; }
        double origPrincipalCD { get; set; }
        double origPrincipalBF { get; set; }
        double penaltyAmount { get; set; }
        Nullable<double> origPrincipalPayment { get; set; }
        Nullable<double> additionalInterestBalance { get; set; }
        byte[] version { get; set; }
    
        Iloan loan { get; set; }
        ICollection<IcontrollerFileDetail> controllerFileDetails { get; set; }
    } 
    
}
