//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IsavingPlan
    {
        int savingPlanID { get; set; }
        int savingID { get; set; }
        System.DateTime plannedDate { get; set; }
        double plannedAmount { get; set; }
        bool deposited { get; set; }
        string creator { get; set; }
        System.DateTime creationDate { get; set; }
        string modifier { get; set; }
        Nullable<System.DateTime> modificationDate { get; set; }
        double amountDeposited { get; set; }
    
        Isaving saving { get; set; }
    } 
    
}
