//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IsavingLienRelease
    {
        int savingLienReleaseId { get; set; }
        int savingLienId { get; set; }
        System.DateTime releaseDate { get; set; }
        double releaseAmount { get; set; }
        int releaseReasonId { get; set; }
        string releaseBy { get; set; }
        string releaseDetail { get; set; }
    
        IlienReleaseReason lienReleaseReason { get; set; }
        IsavingLien savingLien { get; set; }
    } 
    
}
