//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IsavingReservationTransc
    {
        int savingReservationTranscId { get; set; }
        int savingId { get; set; }
        double reservationAmount { get; set; }
        System.DateTime reservationDate { get; set; }
        string reservedBy { get; set; }
        string naration { get; set; }
        string transactionId { get; set; }
        bool committed { get; set; }
        Nullable<System.DateTime> committedDate { get; set; }
        byte reservationTypeId { get; set; }
    
        IreservationType reservationType { get; set; }
        Isaving saving { get; set; }
    } 
    
}
