//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IsavingNextOfKin
    {
        int savingNextOfKinId { get; set; }
        int savingId { get; set; }
        Nullable<System.DateTime> dob { get; set; }
        string otherNames { get; set; }
        string surName { get; set; }
        string relationshipType { get; set; }
        int idTypeId { get; set; }
        string idNumber { get; set; }
        double percentageAllocated { get; set; }
        byte[] picture { get; set; }
        string phoneNumber { get; set; }
    
        IidNoType idNoType { get; set; }
        Isaving saving { get; set; }
    } 
    
}
