//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IstaffAttendance
    {
        int staffAttendanceID { get; set; }
        int staffID { get; set; }
        int yearID { get; set; }
        int monthID { get; set; }
        Nullable<System.DateTime> clockInTime { get; set; }
        Nullable<System.DateTime> clockOutTime { get; set; }
        byte[] version { get; set; }
    
        Imonth month { get; set; }
        Iyear year { get; set; }
        Istaff staff { get; set; }
    } 
    
}
