//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface Isupplier
    {
        int supplierID { get; set; }
        string supplierName { get; set; }
        string directions { get; set; }
        string comments { get; set; }
        double maximumExposure { get; set; }
    
        ICollection<IinvoiceLoan> invoiceLoans { get; set; }
        ICollection<IinvoiceLoanConfig> invoiceLoanConfigs { get; set; }
        ICollection<IsupplierContact> supplierContacts { get; set; }
    } 
    
}
