//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IsusuConfig
    {
        int susuConfigID { get; set; }
        int susuSchemeID { get; set; }
        int defaultActionID { get; set; }
        bool excludeSundays { get; set; }
        bool excludeSaturdays { get; set; }
        int daysInPeriod { get; set; }
        int periodsInCycle { get; set; }
        Nullable<int> contributionsPayableAccountID { get; set; }
        int daysDeductedPerPeriod { get; set; }
        int regularSusuDaysInPeriod { get; set; }
        int regularSusuPeriodsInCycle { get; set; }
        Nullable<int> regularSusuContributionsPayableAccountID { get; set; }
        int regularSusuDaysDeductedPerPeriod { get; set; }
        double dormantInterestRate { get; set; }
        double dormantPenaltyRate { get; set; }
        Nullable<int> regularContributionsPayableAccountID { get; set; }
    
        IsusuScheme susuScheme { get; set; }
    } 
    
}
