//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface IsusuGroup
    {
        int susuGroupID { get; set; }
        int susuGroupNo { get; set; }
        string susuGroupName { get; set; }
    
        ICollection<IsusuAccount> susuAccounts { get; set; }
        ICollection<IsusuGroupHistory> susuGroupHistories { get; set; }
    } 
    
}
