//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public interface Ivw_controllerFile_outstandingLoan
    {
        int clientID { get; set; }
        int loanID { get; set; }
        string staffID { get; set; }
        int fileDetailID { get; set; }
        int fileID { get; set; }
        string managementUnit { get; set; }
        string oldID { get; set; }
        double balBF { get; set; }
        string employeeName { get; set; }
        double monthlyDeduction { get; set; }
        Nullable<double> origAmt { get; set; }
        Nullable<int> repaymentScheduleID { get; set; }
        bool authorized { get; set; }
        bool duplicate { get; set; }
        bool refunded { get; set; }
        bool notFound { get; set; }
        double overage { get; set; }
        string remarks { get; set; }
        string loanNo { get; set; }
        double amountDisbursed { get; set; }
        Nullable<System.DateTime> disbursementDate { get; set; }
        Nullable<long> RecordNumber { get; set; }
        Nullable<int> LoanCount { get; set; }
    } 
    
}
