use coreDB
go


alter PROCEDURE get_op_stmt
(
	@start_date datetime,
	@end_date datetime,
	@no_tx bit,
	@cost_center_id int = null
)
with encryption
AS
BEGIN
declare 
	@tbl TABLE 
(
	acc_num nvarchar(100),
	acc_name nvarchar(100),
	head_name1 nvarchar(100),
	head_name2 nvarchar(100),
	head_name3 nvarchar(100),
	head_name4 nvarchar(100),
	cat_code int,
	cat_name nvarchar(100),
	major_name nvarchar(100),
	major_symbol nvarchar(100),
	loc_amt float,
	frgn_amt float,
	loc_ytd_amt float,
	frgn_ytd_amt float,
	minor_name nvarchar(100),
	minor_symbol nvarchar(100),
	acct_id int,
	head_name5 nvarchar(100),
	head_name6 nvarchar(100),
	head_name7 nvarchar(100),
	currency_id int,
	m1_amt float,
	m2_amt float,
	m3_amt float,
	m4_amt float,
	m5_amt float,
	m6_amt float,
	m7_amt float,
	m8_amt float,
	m9_amt float,
	m10_amt float,
	m11_amt float,
	m12_amt float,
	m1 int,
	m2 int,
	m3 int,
	m4 int,
	m5 int,
	m6 int,
	m7 int,
	m8 int,
	m9 int,
	m10 int,
	m11 int,
	m12 int,
	loc_amt_2 float,
	frgn_amt_2 float,
	loc_ytd_amt_2 float,
	frgn_ytd_amt_2 float,
	m1_amt_2 float,
	m2_amt_2 float,
	m3_amt_2 float,
	m4_amt_2 float,
	m5_amt_2 float,
	m6_amt_2 float,
	m7_amt_2 float,
	m8_amt_2 float,
	m9_amt_2 float,
	m10_amt_2 float,
	m11_amt_2 float,
	m12_amt_2 float,
	loc_amt2 float,
	b1_amt float,
	b2_amt float,
	b3_amt float,
	b4_amt float,
	b5_amt float,
	b6_amt float,
	b7_amt float,
	b8_amt float,
	b9_amt float,
	b10_amt float,
	b11_amt float,
	b12_amt float,
	bud_amt float,
	bud_ytd_amt float,
	acc_amt_2 float
)
	declare @fin_year_start datetime
	declare @fin_year_start_2 datetime
	declare @end_date_2 datetime
	
	select @fin_year_start = dbo.fin_year_start(@end_date)
	select @end_date_2 = dateadd(YY,-1,@end_date)
	select @fin_year_start_2 = dbo.fin_year_start(@end_date_2)
	
	insert into @tbl
	select
		acc_num,
		acc_name,
		isnull(head_name1,''),
		isnull(head_name2,''),
		isnull(head_name3,''),
		isnull(head_name4,''),
		isnull(cat_code,''),
		isnull(cat_name,''),
		isnull(major_name,''),
		isnull(major_symbol,''),
		dbo.acc_amt(acct_id, cat_code, @end_date, 1, @cost_center_id) loc_amt,
		0.0000000000 as frgn_amt,
		dbo.acc_ytd_amt(acct_id, cat_code, @end_date, @cost_center_id) as loc_ytd_amt,
		0.0000000000 as frgn_ytd_amt,
		minor_name,
		minor_symbol,
		acct_id,
		isnull(head_nam5,''),
		isnull(head_name6,''),
		isnull(head_name7,''),
		isnull(currency_id,0),
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 1, @cost_center_id) as m1_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 2, @cost_center_id) as m2_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 3, @cost_center_id) as m3_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 4, @cost_center_id) as m4_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 5, @cost_center_id) as m5_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 6, @cost_center_id) as m6_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 7, @cost_center_id) as m7_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 8, @cost_center_id) as m8_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 9, @cost_center_id) as m9_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 10, @cost_center_id) as m10_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 11, @cost_center_id) as m11_amt,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start, 12, @cost_center_id) as m12_amt,
		m1,
		m2,
		m3,
		m4,
		m5,
		m6,
		m7,
		m8,
		m9,
		m10,
		m11,
		m12,
		dbo.acc_amt(acct_id, cat_code, @end_date_2, 1, @cost_center_id) loc_amt_2,
		0.0000000000 as frgn_amt_2,
		dbo.acc_ytd_amt(acct_id, cat_code, @end_date_2, @cost_center_id) as loc_ytd_amt_2,
		0.0000000000 as frgn_ytd_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 1, @cost_center_id) as m1_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 2, @cost_center_id) as m2_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 3, @cost_center_id) as m3_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 4, @cost_center_id) as m4_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 5, @cost_center_id) as m5_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 6, @cost_center_id) as m6_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 7, @cost_center_id) as m7_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 8, @cost_center_id) as m8_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 9, @cost_center_id) as m9_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 10, @cost_center_id) as m10_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 11, @cost_center_id) as m11_amt_2,
		dbo.acc_amt(acct_id, cat_code, @fin_year_start_2, 12, @cost_center_id) as m12_amt_2,
		dbo.acc_amt2(acct_id, cat_code, @start_date, @end_date, @cost_center_id) as loc_amt2,
		gl.bud_amt(acct_id, DATEADD(month, 0, @fin_year_start), @cost_center_id) as b1_amt,
		gl.bud_amt(acct_id, DATEADD(month, 1, @fin_year_start), @cost_center_id) as b2_amt,
		gl.bud_amt(acct_id, DATEADD(month, 2, @fin_year_start), @cost_center_id) as b3_amt,
		gl.bud_amt(acct_id, DATEADD(month, 3, @fin_year_start), @cost_center_id) as b4_amt,
		gl.bud_amt(acct_id, DATEADD(month, 4, @fin_year_start), @cost_center_id) as b5_amt,
		gl.bud_amt(acct_id, DATEADD(month, 5, @fin_year_start), @cost_center_id) as b6_amt,
		gl.bud_amt(acct_id, DATEADD(month, 6, @fin_year_start), @cost_center_id) as b7_amt,
		gl.bud_amt(acct_id, DATEADD(month, 7, @fin_year_start), @cost_center_id) as b8_amt,
		gl.bud_amt(acct_id, DATEADD(month, 8, @fin_year_start), @cost_center_id) as b9_amt,
		gl.bud_amt(acct_id, DATEADD(month, 9, @fin_year_start), @cost_center_id) as b10_amt,
		gl.bud_amt(acct_id, DATEADD(month, 10, @fin_year_start), @cost_center_id) as b11_amt,
		gl.bud_amt(acct_id, DATEADD(month, 11, @fin_year_start), @cost_center_id) as b12_amt,
		gl.bud_amt(acct_id, @end_date, @cost_center_id) bud_amt,
		gl.bud_ytd_amt(acct_id, @end_date, @cost_center_id) bud_ytd_amt,
		dbo.acc_amt2(acct_id, cat_code, @start_Date, @end_date, @cost_center_id) as acc_amt_2
	from vw_accounts a cross join vw_months
	where cat_code > 3
	
	select * from @tbl 
	where  @no_tx=1 or loc_amt<>0 or loc_ytd_amt<>0 or loc_amt_2<>0 or loc_ytd_amt_2<>0 or loc_amt2>0
		or bud_amt >0 or bud_ytd_amt>0 or acc_amt_2<>0
END
GO