//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class acct_heads
    {
        public acct_heads()
        {
            this.accts = new HashSet<accts>();
        }
    
        public int acct_head_id { get; set; }
        public string head_name { get; set; }
        public Nullable<int> parent_acct_head_id { get; set; }
        public string max_acct_num { get; set; }
        public string min_acct_num { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string last_modifier { get; set; }
        public byte[] version { get; set; }
    
        public virtual acct_cats acct_cats { get; set; }
        public virtual ICollection<accts> accts { get; set; }
    }
}
