//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class acct_cats
    {
        public acct_cats()
        {
            this.acct_heads = new HashSet<acct_heads>();
        }
    
        public int acct_cat_id { get; set; }
        public string cat_name { get; set; }
        public byte cat_code { get; set; }
        public string max_acct_num { get; set; }
        public string min_acct_num { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string last_modifier { get; set; }
    
        public virtual ICollection<acct_heads> acct_heads { get; set; }
    }
}
