//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class comp_prof
    {
        public byte comp_prof_id { get; set; }
        public string comp_name { get; set; }
        public string addr_line_1 { get; set; }
        public string addr_line_2 { get; set; }
        public string phon_num { get; set; }
        public string web { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string email { get; set; }
        public string vat_num { get; set; }
        public double vat_rate { get; set; }
        public double nhil_rate { get; set; }
        public double vat_flat_rate { get; set; }
        public double employee_rate { get; set; }
        public double employer_rate { get; set; }
        public double petty_cash_ceil { get; set; }
        public Nullable<int> currency_id { get; set; }
        public string fax { get; set; }
        public byte fmoy { get; set; }
        public bool num_b4_name { get; set; }
        public bool enf_ou_usg { get; set; }
        public bool enf_ou_sec { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string last_modifier { get; set; }
        public bool edit_posted_jnl { get; set; }
        public double withh_rate { get; set; }
        public double price_per_bag { get; set; }
        public byte[] logo { get; set; }
        public bool deductInsurance { get; set; }
        public bool deductProcFee { get; set; }
        public bool traditionalLoanNo { get; set; }
        public bool disburseLoansToSavingsAccount { get; set; }
        public int defaultInterestTypeID { get; set; }
        public int penaltyMode { get; set; }
        public string ssnitNo { get; set; }
    }
}
