//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class countries
    {
        public countries()
        {
            this.regions = new HashSet<regions>();
        }
    
        public int country_id { get; set; }
        public string country_name { get; set; }
        public string nationality { get; set; }
        public string country_code { get; set; }
        public string abbrev { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string last_modifier { get; set; }
    
        public virtual currencies currencies { get; set; }
        public virtual ICollection<regions> regions { get; set; }
    }
}
