use coreDB
go

alter View vw_op_stmt
with encryption  AS
	select
		'' acc_num,
		'' acc_name,
		'' head_name1,
		'' head_name2,
		'' head_name3,
		'' head_name4,
		0 cat_code,
		'' cat_name,
		'' major_name,
		'' major_symbol,
		isnull(isnull(cast(0 as float ),0),0) as loc_amt,
		isnull(isnull(cast(0 as float ),0),0) as frgn_amt,
		isnull(isnull(cast(0 as float ),0),0) as loc_ytd_amt,
		isnull(isnull(cast(0 as float ),0),0) as bud_ytd_amt,
		isnull(isnull(cast(0 as float ),0),0) as frgn_ytd_amt,
		isnull(isnull(cast(0 as float ),0),0) as bud_amt,
		'' minor_name,
		'' minor_symbol,
		0 acct_id,
		'' head_name5,
		'' head_name6,
		'' head_name7,
		0 currency_id,
		isnull(isnull(cast(0 as float ),0),0) as m1_amt,
		isnull(isnull(cast(0 as float ),0),0) as m2_amt,
		isnull(isnull(cast(0 as float ),0),0) as m3_amt,
		isnull(isnull(cast(0 as float ),0),0) as m4_amt,
		isnull(isnull(cast(0 as float ),0),0) as m5_amt,
		isnull(isnull(cast(0 as float ),0),0) as m6_amt,
		isnull(isnull(cast(0 as float ),0),0) as m7_amt,
		isnull(isnull(cast(0 as float ),0),0) as m8_amt,
		isnull(isnull(cast(0 as float ),0),0) as m9_amt,
		isnull(isnull(cast(0 as float ),0),0) as m10_amt,
		isnull(isnull(cast(0 as float ),0),0) as m11_amt,
		isnull(isnull(cast(0 as float ),0),0) as m12_amt,
		isnull(isnull(cast(0 as float ),0),0) as b1_amt,
		isnull(isnull(cast(0 as float ),0),0) as b2_amt,
		isnull(isnull(cast(0 as float ),0),0) as b3_amt,
		isnull(isnull(cast(0 as float ),0),0) as b4_amt,
		isnull(isnull(cast(0 as float ),0),0) as b5_amt,
		isnull(isnull(cast(0 as float ),0),0) as b6_amt,
		isnull(isnull(cast(0 as float ),0),0) as b7_amt,
		isnull(isnull(cast(0 as float ),0),0) as b8_amt,
		isnull(isnull(cast(0 as float ),0),0) as b9_amt,
		isnull(isnull(cast(0 as float ),0),0) as b10_amt,
		isnull(isnull(cast(0 as float ),0),0) as b11_amt,
		isnull(isnull(cast(0 as float ),0),0) as b12_amt,
		0 as m1,
		0 as m2,
		0 as m3,
		0 as m4,
		0 as m5,
		0 as m6,
		0 as m7,
		0 as m8,
		0 as m9,
		0 as m10,
		0 as m11,
		0 as m12,
		isnull(isnull(cast(0 as float ),0),0) as loc_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as frgn_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as loc_ytd_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as frgn_ytd_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m1_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m2_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m3_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m4_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m5_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m6_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m7_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m8_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m9_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m10_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m11_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as m12_amt_2,
		isnull(isnull(cast(0 as float ),0),0) as loc_amt2,
		isnull(cast(0 as float), 0.0) as acc_amt_2
GO
 