//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankAccountType
    {
        public bankAccountType()
        {
            this.clientBankAccounts = new HashSet<clientBankAccount>();
            this.agents = new HashSet<agent>();
        }
    
        public int accountTypeID { get; set; }
        public string accountTypeName { get; set; }
    
        public virtual ICollection<clientBankAccount> clientBankAccounts { get; set; }
        public virtual ICollection<agent> agents { get; set; }
    }
}
