//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashiersTillDay
    {
        public int cashiersTillDayID { get; set; }
        public int cashiersTillID { get; set; }
        public bool open { get; set; }
        public System.DateTime tillDay { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string last_modifier { get; set; }
        public byte[] version { get; set; }
    
        public virtual cashiersTill cashiersTill { get; set; }
    }
}
