//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashiersTill
    {
        public cashiersTill()
        {
            this.cashierDisbursements = new HashSet<cashierDisbursement>();
            this.cashierReceipts = new HashSet<cashierReceipt>();
            this.cashiersTillDays = new HashSet<cashiersTillDay>();
        }
    
        public int cashiersTillID { get; set; }
        public string userName { get; set; }
        public int accountID { get; set; }
        public byte[] version { get; set; }
    
        public virtual ICollection<cashierDisbursement> cashierDisbursements { get; set; }
        public virtual ICollection<cashierReceipt> cashierReceipts { get; set; }
        public virtual ICollection<cashiersTillDay> cashiersTillDays { get; set; }
    }
}
