//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientActivityLog
    {
        public int clientActivityLogID { get; set; }
        public int clientActivityTypeID { get; set; }
        public System.DateTime activityDate { get; set; }
        public string activityNotes { get; set; }
        public Nullable<System.DateTime> nextActionDate { get; set; }
        public string nextAction { get; set; }
        public int clientID { get; set; }
        public Nullable<int> loanID { get; set; }
        public Nullable<int> responsibleStaffID { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public bool completed { get; set; }
        public byte[] version { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual client client { get; set; }
        public virtual clientActivityType clientActivityType { get; set; }
        public virtual loan loan { get; set; }
    }
}
