//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class depositType
    {
        public depositType()
        {
            this.deposits = new HashSet<deposit>();
        }
    
        public int depositTypeID { get; set; }
        public string depositTypeName { get; set; }
        public double interestRate { get; set; }
        public int defaultPeriod { get; set; }
        public bool allowsInterestWithdrawal { get; set; }
        public bool allowsPrincipalWithdrawal { get; set; }
        public Nullable<int> vaultAccountID { get; set; }
        public Nullable<int> accountsPayableAccountID { get; set; }
        public Nullable<int> interestExpenseAccountID { get; set; }
        public int fxUnrealizedGainLossAccountID { get; set; }
        public int fxRealizedGainLossAccountID { get; set; }
        public int interestCalculationScheduleID { get; set; }
        public Nullable<int> chargesIncomeAccountID { get; set; }
        public Nullable<int> interestPayableAccountID { get; set; }
    
        public virtual ICollection<deposit> deposits { get; set; }
    }
}
