//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public document()
        {
            this.clientDocuments = new HashSet<clientDocument>();
            this.loanDocuments = new HashSet<loanDocument>();
            this.staffDocuments = new HashSet<staffDocument>();
            this.assetDocuments = new HashSet<assetDocument>();
            this.agentDocuments = new HashSet<agentDocument>();
        }
    
        public int documentID { get; set; }
        public byte[] documentImage { get; set; }
        public string description { get; set; }
        public string contentType { get; set; }
        public string fileName { get; set; }
        public byte[] version { get; set; }
    
        public virtual ICollection<clientDocument> clientDocuments { get; set; }
        public virtual ICollection<loanDocument> loanDocuments { get; set; }
        public virtual ICollection<staffDocument> staffDocuments { get; set; }
        public virtual ICollection<assetDocument> assetDocuments { get; set; }
        public virtual ICollection<agentDocument> agentDocuments { get; set; }
    }
}
