//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class employmentType
    {
        public employmentType()
        {
            this.employers = new HashSet<employer>();
        }
    
        public int employmentTypeID { get; set; }
        public string employmentTypeName { get; set; }
    
        public virtual ICollection<employer> employers { get; set; }
    }
}
