//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupCategory
    {
        public int groupCategoryID { get; set; }
        public int clientID { get; set; }
        public Nullable<int> groupID { get; set; }
        public string membershipNo { get; set; }
        public Nullable<System.DateTime> joinDate { get; set; }
        public byte[] version { get; set; }
    
        public virtual client client { get; set; }
        public virtual group group { get; set; }
    }
}
