//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class investmentCharge
    {
        public int investmentChargeID { get; set; }
        public int investmentID { get; set; }
        public int chargeTypeID { get; set; }
        public System.DateTime chargeDate { get; set; }
        public double amount { get; set; }
        public string approvedBy { get; set; }
        public System.DateTime creationDate { get; set; }
        public string memo { get; set; }
    
        public virtual chargeType chargeType { get; set; }
        public virtual investment investment { get; set; }
    }
}
