//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanCheck
    {
        public int loanCheckID { get; set; }
        public Nullable<int> loanID { get; set; }
        public string checkNumber { get; set; }
        public Nullable<int> bankID { get; set; }
        public double checkAmount { get; set; }
        public Nullable<System.DateTime> checkDate { get; set; }
        public bool cashed { get; set; }
        public Nullable<System.DateTime> cashDate { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<int> checkTypeID { get; set; }
        public double balance { get; set; }
        public byte[] version { get; set; }
        public Nullable<int> sourceBankID { get; set; }
    
        public virtual client client { get; set; }
        public virtual checkType checkType { get; set; }
    }
}
