//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class overTime
    {
        public int overTimeID { get; set; }
        public int staffID { get; set; }
        public int payCalendarID { get; set; }
        public double saturdayHours { get; set; }
        public double sundayHours { get; set; }
        public double holidayHours { get; set; }
        public double weekdayAfterWorkHours { get; set; }
        public byte[] version { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual payCalendar payCalendar { get; set; }
    }
}
