//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class prLoanDetail
    {
        public prLoanDetail()
        {
            this.prAllowances = new HashSet<prAllowance>();
        }
    
        public int loanDetailID { get; set; }
        public int loanID { get; set; }
        public string authorityNoteNumber { get; set; }
        public string loanAdvanceNumber { get; set; }
        public double grossSalary { get; set; }
        public double netSalary { get; set; }
        public double socialSecWelfare { get; set; }
        public double tax { get; set; }
        public double totalDeductions { get; set; }
        public double loanDeductionsNotOnPr { get; set; }
        public double amd { get; set; }
        public bool amdPreAuditVerified { get; set; }
        public string amdPreAuditVerifiedBy { get; set; }
        public Nullable<int> loanProductID { get; set; }
        public Nullable<int> loanPurposeID { get; set; }
        public Nullable<int> loanPurposeDetailID { get; set; }
        public string loanPurposeDescription { get; set; }
        public double usedAMD { get; set; }
        public double basicSalary { get; set; }
        public bool isReported { get; set; }
        public bool isSentToController { get; set; }
        public Nullable<int> modeOfEntryID { get; set; }
        public bool incentivePaid { get; set; }
        public string empAddress1 { get; set; }
        public string empAddress2 { get; set; }
        public string empAddressCity { get; set; }
        public string authOfficerName { get; set; }
        public string authOfficerPosition { get; set; }
        public string authOfficerPhone { get; set; }
        public byte[] version { get; set; }
    
        public virtual loan loan { get; set; }
        public virtual loanProduct loanProduct { get; set; }
        public virtual loanPurpose loanPurpose { get; set; }
        public virtual loanPurposeDetail loanPurposeDetail { get; set; }
        public virtual ICollection<prAllowance> prAllowances { get; set; }
        public virtual modeOfEntry modeOfEntry { get; set; }
    }
}
