//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffBenefit
    {
        public int staffBenefitID { get; set; }
        public int staffID { get; set; }
        public double basicSalary { get; set; }
        public string ssn { get; set; }
        public string bankAccountNo { get; set; }
        public string bankName { get; set; }
        public string bankBranchName { get; set; }
        public byte[] version { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
