//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffAddress
    {
        public int staffAddressID { get; set; }
        public int staffID { get; set; }
        public Nullable<int> addressID { get; set; }
        public Nullable<int> addressTypeID { get; set; }
        public byte[] version { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual address address { get; set; }
    }
}
