//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class susuGradePosition
    {
        public int susuGradePositionID { get; set; }
        public int susuGradeID { get; set; }
        public int susuPositionID { get; set; }
        public double amountEntitled { get; set; }
    }
}
