//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class actualPerfomance
    {
        public actualPerfomance()
        {
            this.manufacturingScraps = new HashSet<manufacturingScrap>();
        }
    
        public int actualPerfomanceId { get; set; }
        public int manufacturingCalenderId { get; set; }
        public string duration { get; set; }
        public int durationTypeId { get; set; }
        public double actualQuantity { get; set; }
        public int unitOfMeasurementId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string batchNumber { get; set; }
        public System.DateTime manufacturingDate { get; set; }
        public System.DateTime expiryDate { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual unitOfMeasurement unitOfMeasurement { get; set; }
        public virtual durationType durationType { get; set; }
        public virtual manufacturingCalender manufacturingCalender { get; set; }
        public virtual ICollection<manufacturingScrap> manufacturingScraps { get; set; }
    }
}
