//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class arPayment
    {
        public arPayment()
        {
            this.arPaymentLines = new HashSet<arPaymentLine>();
            this.creditMemoes = new HashSet<creditMemo>();
        }
    
        public long arPaymentId { get; set; }
        public System.DateTime paymentDate { get; set; }
        public double totalAmountPaid { get; set; }
        public int paymentMethodId { get; set; }
        public string checkNumber { get; set; }
        public string creditCardNumber { get; set; }
        public string mobileMoneyNumber { get; set; }
        public bool posted { get; set; }
        public Nullable<System.DateTime> postedDate { get; set; }
        public int currencyId { get; set; }
        public double totalAmountPaidLocal { get; set; }
        public double buyRate { get; set; }
        public double sellRate { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<long> creditMemoId { get; set; }
        public Nullable<long> customerId { get; set; }
        public string paymentNumber { get; set; }
        public Nullable<long> paymentCreditBalance { get; set; }
    
        public virtual paymentMethod paymentMethod { get; set; }
        public virtual ICollection<arPaymentLine> arPaymentLines { get; set; }
        public virtual customer customer { get; set; }
        public virtual ICollection<creditMemo> creditMemoes { get; set; }
    }
}
