//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class durationType
    {
        public durationType()
        {
            this.actualPerfomances = new HashSet<actualPerfomance>();
            this.durationType1 = new HashSet<durationType>();
            this.manufacturingCalenders = new HashSet<manufacturingCalender>();
        }
    
        public int durationTypeId { get; set; }
        public string durationTypeName { get; set; }
        public string durationTypeCode { get; set; }
        public int detailDurationTypeId { get; set; }
    
        public virtual ICollection<actualPerfomance> actualPerfomances { get; set; }
        public virtual ICollection<durationType> durationType1 { get; set; }
        public virtual durationType durationType2 { get; set; }
        public virtual ICollection<manufacturingCalender> manufacturingCalenders { get; set; }
    }
}
