//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryTransferDetail
    {
        public inventoryTransferDetail()
        {
            this.inventoryTransferDetailLines = new HashSet<inventoryTransferDetailLine>();
        }
    
        public int inventoryTransferDetailId { get; set; }
        public int inventoryTransferId { get; set; }
        public long inventoryItemId { get; set; }
        public double quantityTransferred { get; set; }
        public int fromAccountId { get; set; }
        public int toAccountId { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual inventoryItem inventoryItem { get; set; }
        public virtual inventoryTransfer inventoryTransfer { get; set; }
        public virtual ICollection<inventoryTransferDetailLine> inventoryTransferDetailLines { get; set; }
    }
}
