//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobCardLabourDetail
    {
        public long jobCardLabourDetailId { get; set; }
        public long jobCardId { get; set; }
        public System.DateTime labourDate { get; set; }
        public string productionLineDescription { get; set; }
        public System.DateTime starTime { get; set; }
        public System.DateTime endTime { get; set; }
        public string activityCode { get; set; }
        public short totalHours { get; set; }
        public bool billable { get; set; }
        public Nullable<short> billableHours { get; set; }
        public Nullable<double> billingRate { get; set; }
        public Nullable<double> billingValue { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual jobCard jobCard { get; set; }
    }
}
