//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobCardMaterialDetail
    {
        public int jobCardMaterialDetailId { get; set; }
        public long jobCardId { get; set; }
        public string serialNumber { get; set; }
        public string materialDescription { get; set; }
        public long inventoryItemId { get; set; }
        public string partNumber { get; set; }
        public long quantity { get; set; }
        public int unitOfMeasurementId { get; set; }
        public double unitCost { get; set; }
        public double materialCost { get; set; }
        public double markup { get; set; }
        public double materialCharge { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual unitOfMeasurement unitOfMeasurement { get; set; }
        public virtual jobCard jobCard { get; set; }
    }
}
