//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class productMake
    {
        public productMake()
        {
            this.products = new HashSet<product>();
        }
    
        public int productMakeId { get; set; }
        public string productMakeName { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
