//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class shrinkage
    {
        public long shrinkageBatchId { get; set; }
        public long shrinkageId { get; set; }
        public long inventoryItemId { get; set; }
        public double quantityShrunk { get; set; }
        public int unitOfMeasurementId { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<int> shrinkageReasonId { get; set; }
        public string batchNumber { get; set; }
    
        public virtual inventoryItem inventoryItem { get; set; }
        public virtual shrinkageBatch shrinkageBatch { get; set; }
        public virtual shrinkageReason shrinkageReason { get; set; }
        public virtual unitOfMeasurement unitOfMeasurement { get; set; }
    }
}
