//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialityCategory
    {
        public specialityCategory()
        {
            this.specialities = new HashSet<speciality>();
        }
    
        public byte specialityCategoryId { get; set; }
        public string specialityCategoryName { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual ICollection<speciality> specialities { get; set; }
    }
}
