//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coreLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class workOrderActivity
    {
        public long workOrderActivityId { get; set; }
        public long workOrderId { get; set; }
        public string activityCode { get; set; }
        public byte specialityId { get; set; }
        public double hourlyBillingRate { get; set; }
        public double hourlyCost { get; set; }
        public double markup { get; set; }
        public bool billable { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public string modifier { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual speciality speciality { get; set; }
        public virtual workOrder workOrder { get; set; }
    }
}
